#!/bin/bash

osascript -e 'tell application "Finder"' -e 'activate' -e 'open folder "Documents" of folder (short user name of (system info)) of folder "Users" of disk "Macintosh HD"' -e 'end tell'

exit 0
